# Generated by Django 3.1 on 2020-08-10 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScoresAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoremodel',
            name='s_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='ScoresAPI.studentmodel'),
        ),
    ]
